language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

before_install:
  - cd $HOME
  - git clone https://github.com/chocoteam/choco3.git -b develop
  - cd choco3
  - mvn install -DskipTests
