language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

before_install:
  - cd $HOME
  - git clone --depth=50 --branch=develop https://github.com/chocoteam/choco3.git chocoteam/choco3
  - cd chocoteam/choco3
  - mvn install -DskipTests
  - cd $HOME
  - rm -rf $HOME/chocoteam/choco3
