language: java
sudo: false

jdk:
  - oraclejdk8

env:
  - MAVEN_OPTS='-DargLine="-Xmx=1024m"'

install:
  - cd $HOME
  - git clone --depth=50 https://github.com/chocoteam/choco3.git chocoteam/choco3
  - cd chocoteam/choco3
  - mvn install -DskipTests
  - rm -rf $HOME/chocoteam/choco3

before_script: cd $TRAVIS_BUILD_DIR
